// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231210145824_add_map_link_for_restaurant")]
    partial class add_map_link_for_restaurant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("booking_code");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booking_time");

                    b.Property<DateTime?>("CancelledTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_time");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_time");

                    b.Property<DateTime?>("ConfirmedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_time");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("RejectedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_time");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TotalOfPeople")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("total_of_people");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_bookings_member_id");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_bookings_restaurant_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Domain.Deliveries.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_address");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_email");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyTaxCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_tax_code");

                    b.Property<bool>("HasIssueAnInvoice")
                        .HasColumnType("boolean")
                        .HasColumnName("has_issue_an_invoice");

                    b.Property<bool>("HasRequestCutlery")
                        .HasColumnType("boolean")
                        .HasColumnName("has_request_cutlery");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receiver_name");

                    b.Property<string>("ReceivingAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receiving_address");

                    b.HasKey("Id")
                        .HasName("pk_delivery");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_order_id");

                    b.ToTable("delivery", (string)null);
                });

            modelBuilder.Entity("Domain.FreeServices.FeeService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FeeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fee_name");

                    b.Property<float?>("FeePercent")
                        .HasColumnType("real")
                        .HasColumnName("fee_percent");

                    b.Property<int>("FeeType")
                        .HasColumnType("integer")
                        .HasColumnName("fee_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPercent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_percent");

                    b.HasKey("Id")
                        .HasName("pk_fee_service");

                    b.ToTable("fee_service", (string)null);
                });

            modelBuilder.Entity("Domain.Images.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("image_link");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_name");

                    b.HasKey("Id")
                        .HasName("pk_image");

                    b.ToTable("image", (string)null);
                });

            modelBuilder.Entity("Domain.InvoiceDetails.InvoiceDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_invoice_detail");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_detail_invoice_id");

                    b.ToTable("invoice_detail", (string)null);
                });

            modelBuilder.Entity("Domain.InvoiceFees.InvoiceFee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("InvoiceFeeAmount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_fee_amount");

                    b.Property<string>("InvoiceFeeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_fee_name");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("IsPercent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_percent");

                    b.HasKey("Id")
                        .HasName("pk_invoice_fee");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_fee_invoice_id");

                    b.ToTable("invoice_fee", (string)null);
                });

            modelBuilder.Entity("Domain.Invoices.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("OrderType")
                        .HasColumnType("integer")
                        .HasColumnName("order_type");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<int?>("PaymentType")
                        .HasColumnType("integer")
                        .HasColumnName("payment_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("total_quantity");

                    b.HasKey("Id")
                        .HasName("pk_invoice");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_invoice_order_id");

                    b.ToTable("invoice", (string)null);
                });

            modelBuilder.Entity("Domain.MemberActivities.MemberActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_member_activity");

                    b.ToTable("member_activity", (string)null);
                });

            modelBuilder.Entity("Domain.MemberDeviceTokens.MemberDeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_token");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.HasKey("Id")
                        .HasName("pk_member_device_token");

                    b.ToTable("member_device_token", (string)null);
                });

            modelBuilder.Entity("Domain.MemberNotifications.MemberNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsReaded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_readed");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notification_type");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_member_notification");

                    b.ToTable("member_notification", (string)null);
                });

            modelBuilder.Entity("Domain.MemberPointHistories.MemberPointHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<int>("MemberPoint")
                        .HasColumnType("integer")
                        .HasColumnName("member_point");

                    b.Property<int>("PointType")
                        .HasColumnType("integer")
                        .HasColumnName("point_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_member_point_history");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_member_point_history_member_id");

                    b.ToTable("member_point_history", (string)null);
                });

            modelBuilder.Entity("Domain.MemberPointRules.MemberPointRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("PointPerAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("point_per_amount");

                    b.HasKey("Id")
                        .HasName("pk_member_point_rule");

                    b.ToTable("member_point_rule", (string)null);
                });

            modelBuilder.Entity("Domain.MemberVouchers.MemberVoucher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_id");

                    b.HasKey("Id")
                        .HasName("pk_member_voucher");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_member_voucher_member_id");

                    b.HasIndex("VoucherId")
                        .HasDatabaseName("ix_member_voucher_voucher_id");

                    b.ToTable("member_voucher", (string)null);
                });

            modelBuilder.Entity("Domain.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("address");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityId")
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("MemberCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("member_code");

                    b.Property<string>("MemberPlatformIdentityId")
                        .HasColumnType("text")
                        .HasColumnName("member_platform_identity_id");

                    b.Property<Guid?>("MembershipClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_class_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("phone_number");

                    b.Property<int?>("RegisterType")
                        .HasColumnType("integer")
                        .HasColumnName("register_type");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_members_identity_id");

                    b.HasIndex("MembershipClassId")
                        .HasDatabaseName("ix_members_membership_class_id");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Domain.MembershipBenefits.MembershipBenefit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MembershipClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_class_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_member_ship_benefit");

                    b.HasIndex("MembershipClassId")
                        .HasDatabaseName("ix_member_ship_benefit_membership_class_id");

                    b.ToTable("member_ship_benefit", (string)null);
                });

            modelBuilder.Entity("Domain.MembershipClasses.MembershipClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("class_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<float>("PercentBirthDate")
                        .HasColumnType("real")
                        .HasColumnName("percent_birth_date");

                    b.Property<float>("PercentDefault")
                        .HasColumnType("real")
                        .HasColumnName("percent_default");

                    b.HasKey("Id")
                        .HasName("pk_membership_class");

                    b.ToTable("membership_class", (string)null);
                });

            modelBuilder.Entity("Domain.News.News", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_news");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notification_type");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Domain.OrderFees.OrderFee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPercent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_percent");

                    b.Property<string>("OrderFeeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_fee_name");

                    b.Property<string>("OrderFeeValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_fee_value");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.HasKey("Id")
                        .HasName("pk_order_fee");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_fee_order_id");

                    b.ToTable("order_fee", (string)null);
                });

            modelBuilder.Entity("Domain.Orders.LineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("product_image_url");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_line_item");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_line_item_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_line_item_product_id");

                    b.ToTable("line_item", (string)null);
                });

            modelBuilder.Entity("Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("HasPayment")
                        .HasColumnType("boolean")
                        .HasColumnName("has_payment");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_code");

                    b.Property<int>("OrderType")
                        .HasColumnType("integer")
                        .HasColumnName("order_type");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<int?>("PaymentType")
                        .HasColumnType("integer")
                        .HasColumnName("payment_type");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_booking_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_orders_member_id");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_orders_restaurant_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Domain.Partners.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("partner_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("QrCode")
                        .HasColumnType("text")
                        .HasColumnName("qr_code");

                    b.HasKey("Id")
                        .HasName("pk_partner");

                    b.ToTable("partner", (string)null);
                });

            modelBuilder.Entity("Domain.PaymentDetails.PaymentDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<int>("PaymentPlatform")
                        .HasColumnType("integer")
                        .HasColumnName("payment_platform");

                    b.Property<string>("PaymentResponse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_response");

                    b.Property<string>("TransactionRefId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_ref_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_detail");

                    b.HasIndex("InvoiceId")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_detail_invoice_id");

                    b.ToTable("payment_detail", (string)null);
                });

            modelBuilder.Entity("Domain.Permissions.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)")
                        .HasColumnName("resource_name");

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.ToTable("permission", (string)null);
                });

            modelBuilder.Entity("Domain.PhoneValidationCheck.PhoneValidationCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("LastSent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int>("SendCodeCount")
                        .HasColumnType("integer")
                        .HasColumnName("send_code_count");

                    b.HasKey("Id")
                        .HasName("pk_phone_validation_check");

                    b.ToTable("phone_validation_check", (string)null);
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowDelivery")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_delivery");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("product_name");

                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Domain.PromotionToRestaurants.PromotionToRestaurant", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("PromotionId1")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id1");

                    b.Property<Guid?>("RestaurantId1")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id1");

                    b.HasKey("PromotionId", "RestaurantId", "Id")
                        .HasName("pk_promotion_to_restaurant");

                    b.HasIndex("PromotionId1")
                        .HasDatabaseName("ix_promotion_to_restaurant_promotion_id1");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_promotion_to_restaurant_restaurant_id");

                    b.HasIndex("RestaurantId1")
                        .HasDatabaseName("ix_promotion_to_restaurant_restaurant_id1");

                    b.ToTable("promotion-to-restaurant", (string)null);
                });

            modelBuilder.Entity("Domain.Promotions.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("promotion_name");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_promotion");

                    b.ToTable("promotion", (string)null);
                });

            modelBuilder.Entity("Domain.RestaurantAreas.RestaurantArea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("area_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_restaurant_area");

                    b.ToTable("restaurant_area", (string)null);
                });

            modelBuilder.Entity("Domain.Restaurants.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("ClosingAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("closing_at");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("ImageKey")
                        .HasColumnType("text")
                        .HasColumnName("image_key");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MapLink")
                        .HasColumnType("text")
                        .HasColumnName("map_link");

                    b.Property<TimeOnly>("OpeningAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opening_at");

                    b.Property<int>("Operation")
                        .HasColumnType("integer")
                        .HasColumnName("operation");

                    b.Property<Guid>("RestaurantAreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_area_id");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("restaurant_name");

                    b.HasKey("Id")
                        .HasName("pk_restaurants");

                    b.HasIndex("RestaurantAreaId")
                        .HasDatabaseName("ix_restaurants_restaurant_area_id");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("Domain.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_reviews_member_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_reviews_order_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("Domain.RoleToPermissions.RoleToPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_to_permission");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_to_permission_permission_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_to_permission_role_id");

                    b.ToTable("role_to_permission", (string)null);
                });

            modelBuilder.Entity("Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)")
                        .HasColumnName("resource_name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Domain.UserToRoles.UserToRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_to_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_to_role_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_to_role_user_id");

                    b.ToTable("user_to_role", (string)null);
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsUnicode(true)
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Username")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Domain.Vouchers.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conditions")
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<string>("ContentVoucher")
                        .HasColumnType("text")
                        .HasColumnName("content_voucher");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("EndedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_date");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsVoucherDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_voucher_default");

                    b.Property<int?>("LimitQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("limit_quantity");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("Place")
                        .HasColumnType("text")
                        .HasColumnName("place");

                    b.Property<int>("Point")
                        .HasColumnType("integer")
                        .HasColumnName("point");

                    b.Property<string>("QrCode")
                        .HasColumnType("text")
                        .HasColumnName("qr_code");

                    b.Property<string>("QrCodeImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("qr_code_image_url");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TitleVoucher")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title_voucher");

                    b.HasKey("Id")
                        .HasName("pk_voucher");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("ix_voucher_partner_id");

                    b.ToTable("voucher", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xlm");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Domain.Bookings.Booking", b =>
                {
                    b.HasOne("Domain.Members.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_member_member_temp_id");

                    b.HasOne("Domain.Restaurants.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_restaurant_restaurant_temp_id");

                    b.Navigation("Member");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Domain.Deliveries.Delivery", b =>
                {
                    b.HasOne("Domain.Orders.Order", null)
                        .WithOne("Delivery")
                        .HasForeignKey("Domain.Deliveries.Delivery", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_orders_order_id");
                });

            modelBuilder.Entity("Domain.FreeServices.FeeService", b =>
                {
                    b.OwnsOne("Domain.Shared.Money", "FeeAmount", b1 =>
                        {
                            b1.Property<Guid>("FeeServiceId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("fee_amount_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("fee_amount_currency");

                            b1.HasKey("FeeServiceId")
                                .HasName("pk_fee_service");

                            b1.ToTable("fee_service");

                            b1.WithOwner()
                                .HasForeignKey("FeeServiceId")
                                .HasConstraintName("fk_fee_service_fee_service_fee_amount_fee_service_temp_id");
                        });

                    b.Navigation("FeeAmount");
                });

            modelBuilder.Entity("Domain.InvoiceDetails.InvoiceDetail", b =>
                {
                    b.HasOne("Domain.Invoices.Invoice", null)
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_detail_invoice_invoice_temp_id1");

                    b.OwnsOne("Domain.Shared.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("InvoiceDetailId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("price_currency");

                            b1.HasKey("InvoiceDetailId")
                                .HasName("pk_invoice_detail");

                            b1.ToTable("invoice_detail");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceDetailId")
                                .HasConstraintName("fk_invoice_detail_invoice_detail_price_invoice_detail_temp_id");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.InvoiceFees.InvoiceFee", b =>
                {
                    b.HasOne("Domain.Invoices.Invoice", null)
                        .WithMany("InvoiceFees")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_fee_invoice_invoice_temp_id2");

                    b.OwnsOne("Domain.Shared.Money", "FeeChange", b1 =>
                        {
                            b1.Property<Guid>("InvoiceFeeId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("fee_change_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("fee_change_currency");

                            b1.HasKey("InvoiceFeeId")
                                .HasName("pk_invoice_fee");

                            b1.ToTable("invoice_fee");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceFeeId")
                                .HasConstraintName("fk_invoice_fee_invoice_fee_fee_change_invoice_fee_temp_id");
                        });

                    b.Navigation("FeeChange")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Invoices.Invoice", b =>
                {
                    b.HasOne("Domain.Orders.Order", null)
                        .WithOne("Invoice")
                        .HasForeignKey("Domain.Invoices.Invoice", "OrderId")
                        .HasConstraintName("fk_invoice_orders_order_id");

                    b.OwnsOne("Domain.Shared.Money", "TotalBill", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("total_bill_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("total_bill_currency");

                            b1.HasKey("InvoiceId")
                                .HasName("pk_invoice");

                            b1.ToTable("invoice");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId")
                                .HasConstraintName("fk_invoice_invoice_total_bill_invoice_temp_id3");
                        });

                    b.Navigation("TotalBill")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.MemberPointHistories.MemberPointHistory", b =>
                {
                    b.HasOne("Domain.Members.Member", null)
                        .WithMany("MemberPointHistories")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_point_history_member_member_temp_id1");
                });

            modelBuilder.Entity("Domain.MemberPointRules.MemberPointRule", b =>
                {
                    b.OwnsOne("Domain.Shared.Money", "MinimumAmount", b1 =>
                        {
                            b1.Property<Guid>("MemberPointRuleId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("minimum_amount_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("minimum_amount_currency");

                            b1.HasKey("MemberPointRuleId")
                                .HasName("pk_member_point_rule");

                            b1.ToTable("member_point_rule");

                            b1.WithOwner()
                                .HasForeignKey("MemberPointRuleId")
                                .HasConstraintName("fk_member_point_rule_member_point_rule_minimum_amount_member_p");
                        });

                    b.Navigation("MinimumAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.MemberVouchers.MemberVoucher", b =>
                {
                    b.HasOne("Domain.Members.Member", null)
                        .WithMany("MemberVouchers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_voucher_member_member_temp_id2");

                    b.HasOne("Domain.Vouchers.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_voucher_voucher_voucher_temp_id");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Domain.Members.Member", b =>
                {
                    b.HasOne("Domain.MembershipClasses.MembershipClass", "MembershipClass")
                        .WithMany()
                        .HasForeignKey("MembershipClassId")
                        .HasConstraintName("fk_members_membership_class_membership_class_temp_id");

                    b.Navigation("MembershipClass");
                });

            modelBuilder.Entity("Domain.MembershipBenefits.MembershipBenefit", b =>
                {
                    b.HasOne("Domain.MembershipClasses.MembershipClass", null)
                        .WithMany("MembershipBenefits")
                        .HasForeignKey("MembershipClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_ship_benefit_membership_class_membership_class_temp_");
                });

            modelBuilder.Entity("Domain.MembershipClasses.MembershipClass", b =>
                {
                    b.OwnsOne("Domain.Shared.Money", "MaxMoney", b1 =>
                        {
                            b1.Property<Guid>("MembershipClassId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("max_money_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("max_money_currency");

                            b1.HasKey("MembershipClassId")
                                .HasName("pk_membership_class");

                            b1.ToTable("membership_class");

                            b1.WithOwner()
                                .HasForeignKey("MembershipClassId")
                                .HasConstraintName("fk_membership_class_membership_class_max_money_membership_clas");
                        });

                    b.Navigation("MaxMoney")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.OrderFees.OrderFee", b =>
                {
                    b.HasOne("Domain.Orders.Order", null)
                        .WithMany("OrderFees")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_fee_order_order_temp_id2");

                    b.OwnsOne("Domain.Shared.Money", "OrderFeeCharge", b1 =>
                        {
                            b1.Property<Guid>("OrderFeeId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("order_fee_charge_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("order_fee_charge_currency");

                            b1.HasKey("OrderFeeId")
                                .HasName("pk_order_fee");

                            b1.ToTable("order_fee");

                            b1.WithOwner()
                                .HasForeignKey("OrderFeeId")
                                .HasConstraintName("fk_order_fee_order_fee_order_fee_charge_order_fee_temp_id");
                        });

                    b.Navigation("OrderFeeCharge")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Orders.LineItem", b =>
                {
                    b.HasOne("Domain.Orders.Order", null)
                        .WithMany("LineItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_line_item_order_order_temp_id1");

                    b.HasOne("Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_line_item_product_product_temp_id1");

                    b.OwnsOne("Domain.Shared.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("LineItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("price_currency");

                            b1.HasKey("LineItemId")
                                .HasName("pk_line_item");

                            b1.ToTable("line_item");

                            b1.WithOwner()
                                .HasForeignKey("LineItemId")
                                .HasConstraintName("fk_line_item_line_item_price_line_item_temp_id");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Orders.Order", b =>
                {
                    b.HasOne("Domain.Bookings.Booking", "Booking")
                        .WithOne("Order")
                        .HasForeignKey("Domain.Orders.Order", "BookingId")
                        .HasConstraintName("fk_orders_bookings_booking_id");

                    b.HasOne("Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_members_member_id");

                    b.HasOne("Domain.Restaurants.Restaurant", "Restaurant")
                        .WithMany("Orders")
                        .HasForeignKey("RestaurantId")
                        .HasConstraintName("fk_orders_restaurant_restaurant_temp_id1");

                    b.OwnsOne("Domain.Shared.Money", "TotalBill", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("total_bill_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("total_bill_currency");

                            b1.HasKey("OrderId")
                                .HasName("pk_orders");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_order_order_total_bill_order_temp_id3");
                        });

                    b.Navigation("Booking");

                    b.Navigation("Restaurant");

                    b.Navigation("TotalBill")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.PaymentDetails.PaymentDetail", b =>
                {
                    b.HasOne("Domain.Invoices.Invoice", null)
                        .WithOne("PaymentDetail")
                        .HasForeignKey("Domain.PaymentDetails.PaymentDetail", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_detail_invoice_invoice_id");
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.HasOne("Domain.Categories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id1");

                    b.OwnsOne("Domain.Shared.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("price_currency");

                            b1.HasKey("ProductId")
                                .HasName("pk_products");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_product_product_price_product_temp_id");
                        });

                    b.Navigation("Category");

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.PromotionToRestaurants.PromotionToRestaurant", b =>
                {
                    b.HasOne("Domain.Promotions.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_to_restaurant_promotion_promotion_id1");

                    b.HasOne("Domain.Promotions.Promotion", null)
                        .WithMany("PromotionToRestaurants")
                        .HasForeignKey("PromotionId1")
                        .HasConstraintName("fk_promotion_to_restaurant_promotion_promotion_id11");

                    b.HasOne("Domain.Restaurants.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_to_restaurant_restaurant_restaurant_temp_id2");

                    b.HasOne("Domain.Restaurants.Restaurant", null)
                        .WithMany("PromotionToRestaurants")
                        .HasForeignKey("RestaurantId1")
                        .HasConstraintName("fk_promotion_to_restaurant_restaurant_restaurant_temp_id");

                    b.Navigation("Promotion");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Domain.Restaurants.Restaurant", b =>
                {
                    b.HasOne("Domain.RestaurantAreas.RestaurantArea", "RestaurantArea")
                        .WithMany("Restaurants")
                        .HasForeignKey("RestaurantAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_restaurants_restaurant_area_restaurant_area_id");

                    b.OwnsOne("Domain.Restaurants.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_country");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_zip_code");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId")
                                .HasConstraintName("fk_restaurants_restaurants_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("RestaurantArea");
                });

            modelBuilder.Entity("Domain.Reviews.Review", b =>
                {
                    b.HasOne("Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_members_member_id1");

                    b.HasOne("Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_orders_order_id1");
                });

            modelBuilder.Entity("Domain.RoleToPermissions.RoleToPermission", b =>
                {
                    b.HasOne("Domain.Permissions.Permission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_to_permission_permission_permission_temp_id");

                    b.HasOne("Domain.Roles.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_to_permission_role_role_temp_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.UserToRoles.UserToRole", b =>
                {
                    b.HasOne("Domain.Roles.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_to_role_role_role_temp_id1");

                    b.HasOne("Domain.Users.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_to_role_user_user_temp_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Vouchers.Voucher", b =>
                {
                    b.HasOne("Domain.Partners.Partner", "Partner")
                        .WithMany("Vouchers")
                        .HasForeignKey("PartnerId")
                        .HasConstraintName("fk_voucher_partner_partner_temp_id");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Domain.Bookings.Booking", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Invoices.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("InvoiceFees");

                    b.Navigation("PaymentDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Members.Member", b =>
                {
                    b.Navigation("MemberPointHistories");

                    b.Navigation("MemberVouchers");
                });

            modelBuilder.Entity("Domain.MembershipClasses.MembershipClass", b =>
                {
                    b.Navigation("MembershipBenefits");
                });

            modelBuilder.Entity("Domain.Orders.Order", b =>
                {
                    b.Navigation("Delivery");

                    b.Navigation("Invoice");

                    b.Navigation("LineItems");

                    b.Navigation("OrderFees");
                });

            modelBuilder.Entity("Domain.Partners.Partner", b =>
                {
                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Domain.Permissions.Permission", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Domain.Promotions.Promotion", b =>
                {
                    b.Navigation("PromotionToRestaurants");
                });

            modelBuilder.Entity("Domain.RestaurantAreas.RestaurantArea", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("Domain.Restaurants.Restaurant", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PromotionToRestaurants");
                });

            modelBuilder.Entity("Domain.Roles.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
